### ISSUE TITLE
Wrap printf for sifive BSP

### ISSUE THREAD

**Issue by JohnPMerrill** [draperlaboratory/hope-freedom-e-sdk#17]
Currently the sifive BSP has no printf wrapper, so any calls to newlib's printf will fail with a number of policies. We should extend libwrap to contain a printf wrapper identical to the one used in the VCU118 BSP.

**Comment by natestuder** [comment]
This wrapper was added to the 64_bit branch to see if it would correct the heap printing failures.  Though it did not fix the issue, the wrapper should go in as part of that series.

**Comment by natestuder** [comment]
https://github.com/draperlaboratory/hope-freedom-e-sdk/commit/582cda8d6d8ce1f155e4f5d0733ca8d22b79caf7
